/* ============================================
   Conectados - Data Store
   E-mails autorizados (SHA-256) e Perguntas
   ============================================ */

const AUTHORIZED_HASHES = [
    '5cd8aae4e4fa8e44d9b5787f008af3ebe3d5671996dbf48fc219beca5e74e2f2', // igor.resende92@hotmail.com
    '264171cbd9fd365f55a7f91248b32683bc187e198cbbd08a312b59b972745ce9', // danisouzaesilva@gmail.com
];

const QUESTIONS = [
    { id: 1, text: "Me conte qual memória mais feliz em casal você se lembra no último ano." },
    { id: 2, text: "O que você mais gosta no nosso relacionamento atualmente?" },
    { id: 3, text: "O que você mais gostava no relacionamento quando começamos?" },
    { id: 4, text: "Qual minha maior qualidade atualmente?" },
    { id: 5, text: "Diga uma qualidade minha que eu tinha no início, mas perdi." },
    { id: 6, text: "Se você pudesse tirar uma dor minha, qual seria?" },
    { id: 7, text: "Me diga uma coisa que você quer viver comigo no futuro." },
    { id: 8, text: "Se trocássemos de vida por uma semana, o que você acha que mais teria dificuldade em fazer?" },
    { id: 9, text: "Qual a coisa que eu faço que te chateia muito e você nunca me falou?" },
    { id: 10, text: "Tem alguma coisa que você faz, não gosta, mas faz para me agradar?" },
    { id: 11, text: "Qual a coisa que você acha que eu não percebo em você?" },
    { id: 12, text: "Qual foi o momento mais feliz da sua vida?" },
    { id: 13, text: "Se você pudesse mudar alguma coisa na nossa família, o que você mudaria?" },
    { id: 14, text: "O que você considera que eu sou melhor do que outras pessoas?" },
    { id: 15, text: "Qual memória você tem comigo que te deixa com o coração em paz?" },
    { id: 16, text: "Diga 3 coisas que eu faço muito!" },
    { id: 17, text: "Qual coisa sobre mim você acha que ainda vai gostar daqui a 20 anos?" },
    { id: 18, text: "Em algum momento da nossa vida hoje, você se sente sozinho?" },
    { id: 19, text: "Eu sou bom em contar piadas?" },
    { id: 20, text: "Qual o lugar que você mais gosta que eu faça carinho?" },
    { id: 21, text: "Se nós dois fôssemos estranhos e nosso relacionamento fosse um filme, você torceria por esse casal?" },
    { id: 22, text: "Se eu perdesse a memória, qual seria a primeira coisa que você contaria sobre mim?" },
    { id: 23, text: "Qual o meu talento que você mais gosta?" },
    { id: 24, text: "Se eu desaparecesse por 24 horas, qual o primeiro lugar onde você me procuraria?" },
    { id: 25, text: "Me diga uma coisa que você gostaria que eu fizesse sem você precisar pedir." },
    { id: 26, text: "Qual você acredita ser meu maior sonho hoje que ainda não realizei?" },
    { id: 27, text: "Qual a melhor característica que você acha que eu perdi desde que iniciamos o relacionamento?" },
    { id: 28, text: "Se tivéssemos um superpoder como casal, qual seria?" },
    { id: 29, text: "Qual mania minha você acha engraçada?" },
    { id: 30, text: "O que você mais admira em mim?" },
    { id: 31, text: "Se você me perdesse em um supermercado, qual seria o primeiro lugar onde me procuraria?" },
    { id: 32, text: "Qual seria meu crime se eu virasse um supervilão de um filme?" },
    { id: 33, text: "Qual é a coisa que eu faço que mais te irrita?" },
    { id: 34, text: "Se eu te colocasse para fazer todas as minhas tarefas por 1 dia, qual você iria errar primeiro?" },
    { id: 35, text: "Se você tivesse que me conquistar de novo, o que faria?" },
    { id: 36, text: "Qual foi o primeiro presente que você me deu?" },
    { id: 37, text: "Qual foi o último presente que você me deu?" },
    { id: 38, text: "Qual foi o melhor restaurante que fomos juntos?" },
    { id: 39, text: "Qual é a melhor comida que eu faço?" },
    { id: 40, text: "Em que momento você teve certeza que me amava?" },
    { id: 41, text: "Se trocássemos de corpo por um dia, o que você faria primeiro?" },
    { id: 42, text: "Se você pudesse dar um conselho para o \"nós\" de 5 anos atrás, qual seria?" },
    { id: 43, text: "Qual foi a parte de você que mais evoluiu depois de me conhecer?" },
    { id: 44, text: "De todas as pessoas no mundo, por que você me escolheu?" },
    { id: 45, text: "Qual foi a primeira coisa que você contou aos seus amigos sobre mim?" },
    { id: 46, text: "O que você mudou na sua vida por minha causa?" },
    { id: 47, text: "Se eu fosse um vilão de desenho animado, quem eu seria?" },
    { id: 48, text: "Se eu fosse para o BBB, por qual motivo eu seria cancelado(a)?" },
    { id: 49, text: "Qual personagem de desenho ou filme mais parece comigo?" },
    { id: 50, text: "Se pudéssemos escolher qualquer lugar no mundo para morar, onde seria?" },
    { id: 51, text: "O que eu faço que mais te faz se sentir amado(a)?" },
    { id: 52, text: "Se o nosso relacionamento tivesse um aviso no manual de instruções, qual seria?" },
    { id: 53, text: "Qual sonho ou vontade antiga sua, que ficou adormecido(a), eu posso te ajudar a realizar?" },
    { id: 54, text: "Se pudéssemos fazer algo novo juntos, que nunca fizemos, o que você escolheria?" },
    { id: 55, text: "O que você acha que mais mudou em mim desde que iniciamos nosso relacionamento?" },
    { id: 56, text: "Se eu fosse um aplicativo, qual função você mais usa e qual vive dando erro?" },
    { id: 57, text: "Qual você acredita que seja meu prato favorito?" },
    { id: 58, text: "Qual assunto você acha que já conversamos, mas você sente que eu não te entendo?" },
    { id: 59, text: "Quais atitudes minhas te fazem se afastar emocionalmente de mim?" },
    { id: 60, text: "Qual o próximo presente você gostaria de ganhar?" },
    { id: 61, text: "Como você me descreveria para alguém que nunca me viu?" },
    { id: 62, text: "Se pudesse mudar uma coisa no meu comportamento hoje, o que seria?" },
    { id: 63, text: "Vale qualquer pergunta." },
];
